version: 2.1
jobs:
  file-validation:
    docker:
      - image: 'jupyter/pyspark-notebook'
    steps:
      - checkout
      - run: jupyter nbconvert --to notebook --execute notebook_test.ipynb
      - run: ls -al
  deploy:
    docker:
      - image: 'amazon/aws-cli:latest'
        environment:
          AWS_ENV_SET_CMD: 'aws configure set'
          AWS_PROFILE: default
          AWS_OUTPUT: json
          AWS_REGION: us-west-2
    steps:
      - run: ${AWS_ENV_SET_CMD} region ${AWS_REGION}
      - run: ${AWS_ENV_SET_CMD} output ${AWS_OUTPUT}
      - run: ${AWS_ENV_SET_CMD} aws_access_key_id ${AWS_ACCESS_KEY_ID}
      - run: ${AWS_ENV_SET_CMD} aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run: cat ~/.aws/credentials
      - run: cat ~/.aws/config

workflows:
  feature-workflow:
    jobs:
#      - file-validation
      - deploy:
          context:
            - aws-context
#          requires:
#            - file-validation



