version: 2.1
jobs:
  file-validation:
    docker:
      - image: 'jupyter/pyspark-notebook'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: jupyter nbconvert --to notebook --execute notebook_test.ipynb
  deploy:
    docker:
      - image: 'amazon/aws-cli:latest'
        environment:
          AWS_ENV_SET_CMD: 'aws configure set'
          AWS_PROFILE: default
          AWS_OUTPUT: json
          AWS_REGION: us-east-1
          S3_LOCATION: 's3://jeonl-circleci-sec-test'
    steps:
      - attach_workspace:
          at: .
      - run: ls -al
#      - run: aws s3 cp notebook_test.nbconvert.ipynb ${S3_LOCATION}

workflows:
  feature-workflow:
    jobs:
      - file-validation
      - deploy:
          context:
            - aws-context
          requires:
            - file-validation