version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    environment:
      S3_LOCATION: 's3://jeonl-circleci-sec-test'
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: 'echo "Created time: $(date)" > create_file.txt'
      - run: aws s3 cp create_file.txt ${S3_LOCATION}
workflows:
  typical-workflow:
    jobs:
      - aws-cli-example:
          context:
            - aws-context