version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python sample.py

workflows:
  version: 2.1
  build:
    jobs:
      - run-sample
