version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
#  deploy:
#    docker:
#      - image: 'amazon/aws-cli:latest'
#        environment:
#          AWS_ENV_SET_CMD: 'aws configure set'
#          AWS_PROFILE: default
#          AWS_OUTPUT: json
#          AWS_REGION: us-east-1
#          S3_LOCATION: 's3://jeonl-circleci-sec-test'
#    steps:
#      # To use attach_workspace in CircleCI it requires to install tar and gzip commands.
#      - run:
#          name: Install tar and gzip packages
#          command: yum install -y tar gzip
#      # Mount a workspace
#      - attach_workspace:
#          at: .
#      - run:
#          name: Configure AWS configurations
#          command: |
#            mkdir -p ~/.aws && echo -e "[${AWS_PROFILE}]" > ~/.aws/config
#            printf "${AWS_ACCESS_KEY_ID}\n${AWS_SECRET_ACCESS_KEY}\n${AWS_REGION}\n${AWS_OUTPUT}" | aws configure
#      - run:
#          name: Upload the file into S3 bucket
#          command: aws s3 cp notebook_test.nbconvert.ipynb ${S3_LOCATION}
#      - run:
#          name: Capture resources whether it succeeds to upload the file or nor
#          when: always
#          command: echo "Add a capture command here."
workflows:
  typical-workflow:
    jobs:
      - aws-cli-example:
          context:
            - aws-context